apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance-service-deployment
  labels:
    app: insurance-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insurance-service
  template:
    metadata:
      labels:
        app: insurance-service
    spec:
      containers:
      - name: insurance-service
        image: ckurze/insurance-service
        ports:
        - containerPort: 4000
          protocol: TCP
        env:
        - name: ENV
          value: "development"
        - name: PORT
          value: "4000"
        - name: DB
          value: "mongodb://host.docker.internal:27017/insurance"
