apiVersion: v1
kind: Service
metadata:
  name: insurance-service-service
spec:
  selector:
    app: insurance-service
  ports:
  - protocol: TCP
    nodePort: 30001
    port: 4000
    targetPort: 4000
  type: NodePort
